/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tttgame;

import java.awt.event.WindowEvent;
import java.io.FileInputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import sun.awt.TimedWindowEvent;

/**
 *
 * @author Nisal Waduge
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFraim
     */
   
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMultiplyerStrt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSinglePlyrStrt = new javax.swing.JButton();
        btnHowToPlay = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuNewGame = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ටත්   ටික්   ටුක් ");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnMultiplyerStrt.setBackground(new java.awt.Color(204, 204, 255));
        btnMultiplyerStrt.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        btnMultiplyerStrt.setForeground(new java.awt.Color(204, 0, 255));
        btnMultiplyerStrt.setText("Multiplayer");
        btnMultiplyerStrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyerStrtActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nisal Waduge\\Desktop\\TTTGame\\TicTacToeGIF.gif")); // NOI18N

        btnSinglePlyrStrt.setBackground(new java.awt.Color(204, 204, 255));
        btnSinglePlyrStrt.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        btnSinglePlyrStrt.setForeground(new java.awt.Color(204, 0, 255));
        btnSinglePlyrStrt.setText("Singleplayer");
        btnSinglePlyrStrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinglePlyrStrtActionPerformed(evt);
            }
        });

        btnHowToPlay.setBackground(new java.awt.Color(204, 204, 255));
        btnHowToPlay.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        btnHowToPlay.setForeground(new java.awt.Color(204, 0, 0));
        btnHowToPlay.setText("HOW TO PLAY!");
        btnHowToPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHowToPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHowToPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplyerStrt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinglePlyrStrt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSinglePlyrStrt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMultiplyerStrt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHowToPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mnuNewGame.setText("File");

        jMenuItem2.setText("Single Player Mode");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuNewGame.add(jMenuItem2);

        jMenuItem1.setText("Multi Player Mode");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuNewGame.add(jMenuItem1);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuNewGame.add(mnuExit);

        jMenuBar1.add(mnuNewGame);

        jMenu2.setText("About");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Info");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try{ FileInputStream fi=new FileInputStream("C:\\Users\\Nisal Waduge\\Desktop\\TTTGame\\smb_pipe.wav");
       AudioStream  as=new AudioStream(fi);
        AudioPlayer.player.start(as);
        
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        MainFrame2 mf2=new MainFrame2();
        TTTGame t=new TTTGame();
        mf2.setVisible(true);
        AudioPlayer.player.stop(t.as);
        setVisible(false);
      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnMultiplyerStrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyerStrtActionPerformed
        // TODO add your handling code here:
        jMenuItem1ActionPerformed(evt);
        setVisible(false);
       // AudioPlayer.player.stop(as);
    }//GEN-LAST:event_btnMultiplyerStrtActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Nisal Waduge Creations 2015");
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void btnSinglePlyrStrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinglePlyrStrtActionPerformed
        // TODO add your handling code here:
        jMenuItem2ActionPerformed(evt);
        setVisible(false);
         
    }//GEN-LAST:event_btnSinglePlyrStrtActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         try{ FileInputStream fi=new FileInputStream("C:\\Users\\Nisal Waduge\\Desktop\\TTTGame\\smb_pipe.wav");
       AudioStream  as=new AudioStream(fi);
        AudioPlayer.player.start(as);
        
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        MainFrame3 mf3=new MainFrame3();
        TTTGame t=new TTTGame();
        mf3.setVisible(true);
        AudioPlayer.player.stop(t.as);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        int option=  JOptionPane.showConfirmDialog(this, "Are you sure?", "Exit",JOptionPane.YES_NO_OPTION);
     // System.out.println(option);
     if(option==JOptionPane.YES_OPTION)  
         System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void btnHowToPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHowToPlayActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Make three 'X's in line to Win\n\tGood Luck!");
    }//GEN-LAST:event_btnHowToPlayActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Nisal Waduge Creations 2015\n\t\t\t              TicTacToe");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHowToPlay;
    private javax.swing.JButton btnMultiplyerStrt;
    private javax.swing.JButton btnSinglePlyrStrt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuNewGame;
    // End of variables declaration//GEN-END:variables
}
